export const ADD_STUDENT = 'ADD_STUDENT';
export const GET_STUDENTS = 'GET_GSTUDENT';
export const GET_STUDENT = 'GET_STUDENT';
export const DELETE_STUDENT = 'DELETE_STUDENT';
export const UPDATE_STUDENT = 'UPDATE_STUDENT';
export const LOADING_STUDENTS = 'LOADING_STUDENTS';
export const CLEAR_STUDENTS = 'CLEAR_STUDENTS';



